-- 성분사전 스타터 세트. 식약처 화장품 성분사전 전체 연동 전까지 PRD 섹션 3(카테고리별 컨선 특화 성분)과
-- 일반적으로 알려진 접촉성 알레르기 유발 성분을 기준으로 구성한 시작 데이터.
-- irritant_report_count는 실제 trouble_reports 누적으로만 올라가야 하므로 0으로 둔다.
INSERT INTO "public"."ingredients" ("inci_name", "korean_name", "cas_number") VALUES
  ('Niacinamide', '나이아신아마이드', '98-92-0'),
  ('Ascorbic Acid', '아스코빅애씨드', '50-81-7'),
  ('Retinol', '레티놀', '68-26-8'),
  ('Adenosine', '아데노신', '58-61-7'),
  ('Salicylic Acid', '살리실릭애씨드', '69-72-7'),
  ('Melaleuca Alternifolia (Tea Tree) Leaf Oil', '티트리잎오일', NULL),
  ('Panthenol', '판테놀', '81-13-0'),
  ('Allantoin', '알란토인', '97-59-6'),
  ('Centella Asiatica Extract', '병풀추출물', NULL),
  ('Ceramide NP', '세라마이드엔피', NULL),
  ('Squalane', '스쿠알란', '111-01-3'),
  ('Hyaluronic Acid', '히알루론산', '9004-61-9'),
  ('Dimethicone', '디메치콘', '9006-65-9'),
  ('Titanium Dioxide', '티타늄디옥사이드', '13463-67-7'),
  ('Zinc Oxide', '징크옥사이드', '1314-13-2'),
  ('Ethylhexyl Methoxycinnamate', '에틸헥실메톡시신나메이트', '5466-77-3'),
  ('Cocamidopropyl Betaine', '코카미도프로필베타인', '61789-40-0'),
  ('Sodium Cocoyl Isethionate', '소듐코코일이세치오네이트', '61789-32-0'),
  ('Sodium Lauryl Sulfate', '소듐라우릴설페이트', '151-21-3'),
  ('Sodium Laureth Sulfate', '소듐라우레스설페이트', '9004-82-4'),
  ('Alcohol Denat.', '변성알코올', '64-17-5'),
  ('Parfum', '향료', NULL),
  ('Limonene', '리모넨', '5989-27-5'),
  ('Linalool', '리날룰', '78-70-6'),
  ('Citronellol', '시트로넬롤', '106-22-9'),
  ('Geraniol', '제라니올', '106-24-1'),
  ('Methylisothiazolinone', '메칠이소치아졸리논', '2682-20-4'),
  ('Methylparaben', '메칠파라벤', '99-76-3'),
  ('Propylparaben', '프로필파라벤', '94-13-3'),
  ('Copper Tripeptide-1', '카퍼트라이펩타이드-1', NULL),
  ('Avobenzone', '아보벤존', '70356-09-1'),
  ('Glycolic Acid', '글라이콜릭애씨드', '79-14-1'),
  ('Lactic Acid', '락틱애씨드', '50-21-5'),
  ('Tocopherol', '토코페롤', '59-02-9'),
  ('Panax Ginseng Root Extract', '인삼뿌리추출물', NULL),
  ('Butylene Glycol', '부틸렌글라이콜', '107-88-0'),
  ('Glycerin', '글리세린', '56-81-5'),
  ('Mentha Piperita (Peppermint) Oil', '페퍼민트오일', '8006-90-4')
ON CONFLICT ("inci_name") DO NOTHING;
